### ISSUE TITLE
errors when starting.

### ISSUE THREAD

**Issue by crzykidd** [tg44/mqtt-prometheus-message-exporter#6]
I am trying to pull metrics from Tasmota device,  I am using a pretty basic patterns.  Which I think is correct:

`  "patterns": [
    { 
      "prefix": "backdeck_node_1",
      "pattern": "tele/<<device>>/[[prefix]]/|/[[prefixes]]"
    }
  ]`
Almost the same as your example except the node is backdeck_node_1 instead of tasmota.  

When I kick this off in docker I get the following errors:  https://pastebin.com/hDMrvHhQ

Not sure if it is my pattern syntax or something else? Any input would be appreciated.  

Thank you,

**Comment by tg44** [comment]
Wow! Why we get debug level logs? I will check this tomorrow, I have a new cluster with new iot devices to set up anyway.

Btw do you get out any metrics from the metrics endpoint?

**Comment by crzykidd** [comment]
Here is the output from the metrics endpoing:
```
# HELP mqtt_exporter_uptime The uptime of the mqtt-exporter
# TYPE mqtt_exporter_uptime counter
mqtt_exporter_uptime 19.0
```

and my docker-compose.yml
```
  mqtt-prom-exp:
    restart: unless-stopped
    image: tg44/mqtt-prometheus-message-exporter
    volumes:
      - /docker/mqtt2prometheus/exporter.conf:/app/exporter.conf
    ports:
      - "9324:9000"
    environment:
      - 'CONF_PATH=/app/exporter.conf'
```

and my exporter.conf
```
{
  "selfMetrics": {
    "prefix": "mqtt_exporter"
  },
  "mqtt": {
    "host": "192.168.50.11",
    "port": 1883,
    "username": "username",
    "password": "sOmePaSSw0rd",
    "maxPacketSize": 4096
  },
  "patterns": [
    {
      "prefix": "backdeck_node_1",
      "pattern": "tele/<<device>>/[[prefix]]/|/[[prefixes]]"
    }
  ]
}
```
